version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-crud-student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  back-end:
    image: youssoudiarra/crud-student:v.1.1
    container_name: crud-student-backend
    ports:
      - "8085:8085"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/spring-crud-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      spring.datasource.username: user
      spring.datasource.password: user
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xmx64M
    depends_on:
      - mysql
    links:
      - mysql
    profiles:
      - all

  redis:
    image: redis:5.0.3-alpine
    container_name: crud-student-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
