version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: crud-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      springboot-mysql-net:

  back-end-student:
    image: youssoudiarra/crud-student:v.1.1
    container_name: crud-student-backend
    ports:
      - 8889:8889
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/crud-db
      - spring.datasource.username=user
      - spring.datasource.password=user
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
    links:
      - mysql
    profiles:
      - all
    networks:
      springboot-mysql-net:

networks:
   springboot-mysql-net:

