version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    profiles:
      - all

  back-end:
    image: youssoudiarra/crud-student:v.1.1
    container_name: spring-rest-backend
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/crud-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_CACHE_TYPE: redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xms512M -Xmx1g
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    profiles:
      - all

  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    profiles:
      - all

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
