version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-crud-student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysql ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  back-end-student:
    image: youssoudiarra/crud-student:v.1.1
    container_name: crud-student-backend
    ports:
      - 8889:8889
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/crud-db
      - spring.datasource.username=user
      - spring.datasource.password=user
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
    links:
      - mysql
    profiles:
      - all


  redis:
    image: redis:5.0.3-alpine
    container_name: crud-student-redis
    ports:
      - 6379:6379

volumes:
  mysql_data:
    driver: local





