#server:
#  port: 8080
#spring:
#  datasource:
#    username: root
#    password:
#    url: jdbc:mysql://localhost:3306/spring-training?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
#    hibernate:
#      use-new-id-generator-mappings: false
server:
  port: 8080
spring:
  datasource:
    username: user
    password: user
    url: jdbc:mysql://mysql:3306/spring-training?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
