server:
  port: 8083

spring:
  datasource:
    password:
    url: jdbc:mysql://127.0.0.1:3306/crud-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
#pour le deploiement sur docker meme port avec le docker compose et le username doit etre identique

