
spring:
  datasource:
    password: user
    url: jdbc:mysql://localhost:3307/crud-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    username: user
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false

